/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-20 at 22:08:55 UTC 
 * Modify at your own risk.
 */

package com.moodstream.model.photoendpoint.model;

/**
 * Model definition for Photo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the photoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Photo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String blobPath;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String caption;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long eventId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ownerNickname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long uploadTime;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBlobPath() {
    return blobPath;
  }

  /**
   * @param blobPath blobPath or {@code null} for none
   */
  public Photo setBlobPath(java.lang.String blobPath) {
    this.blobPath = blobPath;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCaption() {
    return caption;
  }

  /**
   * @param caption caption or {@code null} for none
   */
  public Photo setCaption(java.lang.String caption) {
    this.caption = caption;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEventId() {
    return eventId;
  }

  /**
   * @param eventId eventId or {@code null} for none
   */
  public Photo setEventId(java.lang.Long eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOwnerNickname() {
    return ownerNickname;
  }

  /**
   * @param ownerNickname ownerNickname or {@code null} for none
   */
  public Photo setOwnerNickname(java.lang.String ownerNickname) {
    this.ownerNickname = ownerNickname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUploadTime() {
    return uploadTime;
  }

  /**
   * @param uploadTime uploadTime or {@code null} for none
   */
  public Photo setUploadTime(java.lang.Long uploadTime) {
    this.uploadTime = uploadTime;
    return this;
  }

  @Override
  public Photo set(String fieldName, Object value) {
    return (Photo) super.set(fieldName, value);
  }

  @Override
  public Photo clone() {
    return (Photo) super.clone();
  }

}
