/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-10-31 at 01:32:23 UTC 
 * Modify at your own risk.
 */

package com.moodstream.model.checkinendpoint;

/**
 * Service definition for Checkinendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CheckinendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Checkinendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the checkinendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://moodstreamers.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "checkinendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Checkinendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Checkinendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCheckin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link GetCheckin#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetCheckin getCheckin(java.lang.Long id) throws java.io.IOException {
    GetCheckin result = new GetCheckin(id);
    initialize(result);
    return result;
  }

  public class GetCheckin extends CheckinendpointRequest<com.moodstream.model.checkinendpoint.model.Checkin> {

    private static final String REST_PATH = "checkin/{id}";

    /**
     * Create a request for the method "getCheckin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link GetCheckin#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCheckin#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCheckin(java.lang.Long id) {
      super(Checkinendpoint.this, "GET", REST_PATH, null, com.moodstream.model.checkinendpoint.model.Checkin.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCheckin setAlt(java.lang.String alt) {
      return (GetCheckin) super.setAlt(alt);
    }

    @Override
    public GetCheckin setFields(java.lang.String fields) {
      return (GetCheckin) super.setFields(fields);
    }

    @Override
    public GetCheckin setKey(java.lang.String key) {
      return (GetCheckin) super.setKey(key);
    }

    @Override
    public GetCheckin setOauthToken(java.lang.String oauthToken) {
      return (GetCheckin) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCheckin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCheckin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCheckin setQuotaUser(java.lang.String quotaUser) {
      return (GetCheckin) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCheckin setUserIp(java.lang.String userIp) {
      return (GetCheckin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCheckin setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCheckin set(String parameterName, Object value) {
      return (GetCheckin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCheckin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link InsertCheckin#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.moodstream.model.checkinendpoint.model.Checkin}
   * @return the request
   */
  public InsertCheckin insertCheckin(com.moodstream.model.checkinendpoint.model.Checkin content) throws java.io.IOException {
    InsertCheckin result = new InsertCheckin(content);
    initialize(result);
    return result;
  }

  public class InsertCheckin extends CheckinendpointRequest<com.moodstream.model.checkinendpoint.model.Checkin> {

    private static final String REST_PATH = "checkin";

    /**
     * Create a request for the method "insertCheckin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link InsertCheckin#execute()} method to invoke the remote
     * operation. <p> {@link InsertCheckin#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.moodstream.model.checkinendpoint.model.Checkin}
     * @since 1.13
     */
    protected InsertCheckin(com.moodstream.model.checkinendpoint.model.Checkin content) {
      super(Checkinendpoint.this, "POST", REST_PATH, content, com.moodstream.model.checkinendpoint.model.Checkin.class);
    }

    @Override
    public InsertCheckin setAlt(java.lang.String alt) {
      return (InsertCheckin) super.setAlt(alt);
    }

    @Override
    public InsertCheckin setFields(java.lang.String fields) {
      return (InsertCheckin) super.setFields(fields);
    }

    @Override
    public InsertCheckin setKey(java.lang.String key) {
      return (InsertCheckin) super.setKey(key);
    }

    @Override
    public InsertCheckin setOauthToken(java.lang.String oauthToken) {
      return (InsertCheckin) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCheckin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCheckin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCheckin setQuotaUser(java.lang.String quotaUser) {
      return (InsertCheckin) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCheckin setUserIp(java.lang.String userIp) {
      return (InsertCheckin) super.setUserIp(userIp);
    }

    @Override
    public InsertCheckin set(String parameterName, Object value) {
      return (InsertCheckin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "isCheckedin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link IsCheckedin#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @param eventId
   * @return the request
   */
  public IsCheckedin isCheckedin(java.lang.String userId, java.lang.Long eventId) throws java.io.IOException {
    IsCheckedin result = new IsCheckedin(userId, eventId);
    initialize(result);
    return result;
  }

  public class IsCheckedin extends CheckinendpointRequest<com.moodstream.model.checkinendpoint.model.Checkin> {

    private static final String REST_PATH = "isCheckedin/{userId}/{eventId}";

    /**
     * Create a request for the method "isCheckedin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link IsCheckedin#execute()} method to invoke the remote
     * operation. <p> {@link
     * IsCheckedin#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param userId
     * @param eventId
     * @since 1.13
     */
    protected IsCheckedin(java.lang.String userId, java.lang.Long eventId) {
      super(Checkinendpoint.this, "POST", REST_PATH, null, com.moodstream.model.checkinendpoint.model.Checkin.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.eventId = com.google.api.client.util.Preconditions.checkNotNull(eventId, "Required parameter eventId must be specified.");
    }

    @Override
    public IsCheckedin setAlt(java.lang.String alt) {
      return (IsCheckedin) super.setAlt(alt);
    }

    @Override
    public IsCheckedin setFields(java.lang.String fields) {
      return (IsCheckedin) super.setFields(fields);
    }

    @Override
    public IsCheckedin setKey(java.lang.String key) {
      return (IsCheckedin) super.setKey(key);
    }

    @Override
    public IsCheckedin setOauthToken(java.lang.String oauthToken) {
      return (IsCheckedin) super.setOauthToken(oauthToken);
    }

    @Override
    public IsCheckedin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (IsCheckedin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public IsCheckedin setQuotaUser(java.lang.String quotaUser) {
      return (IsCheckedin) super.setQuotaUser(quotaUser);
    }

    @Override
    public IsCheckedin setUserIp(java.lang.String userIp) {
      return (IsCheckedin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public IsCheckedin setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long eventId;

    /**

     */
    public java.lang.Long getEventId() {
      return eventId;
    }

    public IsCheckedin setEventId(java.lang.Long eventId) {
      this.eventId = eventId;
      return this;
    }

    @Override
    public IsCheckedin set(String parameterName, Object value) {
      return (IsCheckedin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCheckin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link ListCheckin#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCheckin listCheckin() throws java.io.IOException {
    ListCheckin result = new ListCheckin();
    initialize(result);
    return result;
  }

  public class ListCheckin extends CheckinendpointRequest<com.moodstream.model.checkinendpoint.model.CollectionResponseCheckin> {

    private static final String REST_PATH = "checkin";

    /**
     * Create a request for the method "listCheckin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link ListCheckin#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListCheckin#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCheckin() {
      super(Checkinendpoint.this, "GET", REST_PATH, null, com.moodstream.model.checkinendpoint.model.CollectionResponseCheckin.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCheckin setAlt(java.lang.String alt) {
      return (ListCheckin) super.setAlt(alt);
    }

    @Override
    public ListCheckin setFields(java.lang.String fields) {
      return (ListCheckin) super.setFields(fields);
    }

    @Override
    public ListCheckin setKey(java.lang.String key) {
      return (ListCheckin) super.setKey(key);
    }

    @Override
    public ListCheckin setOauthToken(java.lang.String oauthToken) {
      return (ListCheckin) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCheckin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCheckin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCheckin setQuotaUser(java.lang.String quotaUser) {
      return (ListCheckin) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCheckin setUserIp(java.lang.String userIp) {
      return (ListCheckin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCheckin setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCheckin setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCheckin set(String parameterName, Object value) {
      return (ListCheckin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCheckin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link RemoveCheckin#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCheckin removeCheckin(java.lang.Long id) throws java.io.IOException {
    RemoveCheckin result = new RemoveCheckin(id);
    initialize(result);
    return result;
  }

  public class RemoveCheckin extends CheckinendpointRequest<Void> {

    private static final String REST_PATH = "checkin/{id}";

    /**
     * Create a request for the method "removeCheckin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCheckin#execute()} method to invoke the remote
     * operation. <p> {@link RemoveCheckin#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCheckin(java.lang.Long id) {
      super(Checkinendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCheckin setAlt(java.lang.String alt) {
      return (RemoveCheckin) super.setAlt(alt);
    }

    @Override
    public RemoveCheckin setFields(java.lang.String fields) {
      return (RemoveCheckin) super.setFields(fields);
    }

    @Override
    public RemoveCheckin setKey(java.lang.String key) {
      return (RemoveCheckin) super.setKey(key);
    }

    @Override
    public RemoveCheckin setOauthToken(java.lang.String oauthToken) {
      return (RemoveCheckin) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCheckin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCheckin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCheckin setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCheckin) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCheckin setUserIp(java.lang.String userIp) {
      return (RemoveCheckin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCheckin setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCheckin set(String parameterName, Object value) {
      return (RemoveCheckin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCheckin".
   *
   * This request holds the parameters needed by the the checkinendpoint server.  After setting any
   * optional parameters, call the {@link UpdateCheckin#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.moodstream.model.checkinendpoint.model.Checkin}
   * @return the request
   */
  public UpdateCheckin updateCheckin(com.moodstream.model.checkinendpoint.model.Checkin content) throws java.io.IOException {
    UpdateCheckin result = new UpdateCheckin(content);
    initialize(result);
    return result;
  }

  public class UpdateCheckin extends CheckinendpointRequest<com.moodstream.model.checkinendpoint.model.Checkin> {

    private static final String REST_PATH = "checkin";

    /**
     * Create a request for the method "updateCheckin".
     *
     * This request holds the parameters needed by the the checkinendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCheckin#execute()} method to invoke the remote
     * operation. <p> {@link UpdateCheckin#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.moodstream.model.checkinendpoint.model.Checkin}
     * @since 1.13
     */
    protected UpdateCheckin(com.moodstream.model.checkinendpoint.model.Checkin content) {
      super(Checkinendpoint.this, "PUT", REST_PATH, content, com.moodstream.model.checkinendpoint.model.Checkin.class);
    }

    @Override
    public UpdateCheckin setAlt(java.lang.String alt) {
      return (UpdateCheckin) super.setAlt(alt);
    }

    @Override
    public UpdateCheckin setFields(java.lang.String fields) {
      return (UpdateCheckin) super.setFields(fields);
    }

    @Override
    public UpdateCheckin setKey(java.lang.String key) {
      return (UpdateCheckin) super.setKey(key);
    }

    @Override
    public UpdateCheckin setOauthToken(java.lang.String oauthToken) {
      return (UpdateCheckin) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCheckin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCheckin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCheckin setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCheckin) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCheckin setUserIp(java.lang.String userIp) {
      return (UpdateCheckin) super.setUserIp(userIp);
    }

    @Override
    public UpdateCheckin set(String parameterName, Object value) {
      return (UpdateCheckin) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Checkinendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Checkinendpoint}. */
    @Override
    public Checkinendpoint build() {
      return new Checkinendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CheckinendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCheckinendpointRequestInitializer(
        CheckinendpointRequestInitializer checkinendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(checkinendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
